name: ASH Daily Scan

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ash:
    uses: awslabs/automated-security-helper/.github/workflows/run-ash-security-scan.yml@v3.5.3
    permissions:
      contents: read
      checks: write
      pull-requests: write
      security-events: write
    with:
      ash-version: "v3.5.3"
      collect-sarif-report: true
      post-pr-comment: false
      verbose: true
      install-grype: true
      install-syft: true
      install-opengrep: true
